agend/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from .models import *
from . import views
from .views import *
app_name = 'agend'

urlpatterns = [
    path('', AgendaListView.as_view(), name='agenda'),
    
] 
 
 
 
 

cytiesweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('agend/', include('agend.urls')),
    path('galeria/', include('galeria.urls')),
    ]

if settings.DEBUG:urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

galeria/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from .models import *
from . import views
from .views import *

urlpatterns = [
    path('', ImagenListView.as_view(), name='galeria'),
    
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse
from . import views
from .views import *


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('servicios/', ServiciosView.as_view(), name='servicios'),
    path('centros/', CentrosView.as_view(), name='centros'),
    
] 

agend/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Agenda(models.Model):
    titulo_agenda = models.CharField (max_length = 50, primary_key = True)
    bajada_titulo_agenda = models.CharField(max_length = 50)
    texto_agenda = models.TextField()
    imagen_agenda = models.ImageField(upload_to="static")
    imagen_agenda_dos = models.ImageField(upload_to="static")
    fechapublicacion_agenda = models.DateTimeField()
       # HERE 
    def __str__(self):
        return'%s %s'%(self.titulo_agenda,self.fechapublicacion_agenda)

galeria/models.py
from django.db import models

class Imagen(models.Model):
   imagen_archivo = models.ImageField(upload_to="gallery")
   nombre_imagen = models.CharField(max_length=200)
   descripcion_imagen = models.TextField()

   def __str__(self):
        return self.nombre_imagen
# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

agend/views.py
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import render, get_object_or_404
from  .models import Agenda
from django.urls import reverse
from django.utils import timezone
from django.views import generic


class AgendaListView(generic.ListView):
    model = Agenda
    template_name = 'agend/agenda.html'
class AgendaDetailView(generic.DetailView):
    model = Agenda
    template_name = 'agend/agenda_detail.html'
    slug_field = 'titulo_agenda'

galeria/views.py
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from galeria.models import Imagen
from django.utils import timezone
from django.views import generic


class ImagenListView(generic.ListView):
    model = Imagen
    template_name = 'galeria/galeria.html'

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

class HomePageView(TemplateView):
    template_name = 'pages/home.html'

class AboutView(TemplateView):
    template_name = 'pages/about.html'

class ServiciosView(TemplateView):
    template_name = 'pages/servicios.html'

class CentrosView(TemplateView):
    template_name = 'pages/centros.html'

templates/agend/agenda.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{# CSS Bootstrap #}
{% bootstrap_css %}
{% block content %}
<br>
<br>
<br>
<br>
<section id="agenda">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <h2 style="text-align: center ;color: #1e4f99">Centros y Laboratorios </h2>
        <hr class="divider my-4">
        {% if agenda_list %}
        {% for agenda in agenda_list %} 
        <section id="agenda">
        <div class="container">
            <div class="card mb-3" style="width: 40rem;">
                <img src="{{agenda.imagen_agenda.url}}" class="card-img-top" alt="{{agenda.titulo_agenda}}">
                <div class="card-body">
                  <h5 class="card-title"><a href="{{agenda.pk}}">{{agenda.titulo_agenda}}</a></h5>
                  <p class="card-text" style="text-align: justify"><small class="text-muted">{{fechapublicacion_agenda}} </small></p>
                  <br>
                  <br>
                  <p class="card-text" style="text-align: justify">{{agenda.texto_agenda}}</p>
                  <a href="{{agenda.pk}}" class="btn btn-primary">ver más...</a>
                </div>
              </div>
        </div>
        </section>
        {% endfor %} 
        <br>
        <br>
        <br>
      </div>
    </div>
  </div>
</section>   
<br>
<br>
<br>
    </ul>
    {% else %}
      <h1>No se encontraron agenda </h1>
    {% endif %}  

{% endblock content %}

templates/agend/agenda_detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{# CSS Bootstrap #}
{% bootstrap_css %}
{% block content %}
<br>
<br>
<br>
<br>
<section id="agenda">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto">
          <p style="text-align: justify"><small class="text-muted">{{agenda.fechapublicacion_agenda}} </small></p>
        <h2 style="text-align: center ;color: #1e4f99"> <a href="{{agenda.pk}}">{{agenda.titulo_agenda}}</a></h2>
        <h4 style="text-align: center ;color: #1e4f99"> {{agenda.bajada_titulo_agenda}} </h4>
        
        
   
    
          <hr class="divider my-4">
        <section id="agenda">
        <div class="container">
            <div class="card mb-3" style="width: 40rem;">
                <img src="{{agenda.imagen_agenda.url}}" class="card-img-top" alt="{{agenda.titulo_agenda}}">
                <br>
                <div class="card-body">
                  <br>
                  <p class="card-text" style="text-align: justify">{{agenda.texto_agenda}}</p>
                </div>
                <img src="{{agenda.imagen_agenda_dos.url}}" class="card-img-top" alt="{{agenda.titulo_agenda}}">
              </div>
        </div>
        </section>
        
        <br>
        <br>
        <br>
      </div>
    </div>
  </div>
</section>   
<br>
<br>
<br>
    
{% endblock content%}

templates/base.html
{% load static %}
{% load bootstrap4 %}
{# CSS Bootstrap #}
{% bootstrap_css %}
 
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>CYTIES - Investigacion y Desarrollo</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/base.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src='main.js'></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">
</head>
<body>
    <!-- Navigation -->
  <nav style="background-color:rgba(255, 255, 255, 0.582)" class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
      <div class="container">
        <img src="/static/img/logo1.png" height="50">
        <img src="/static/img/logo2.png"height="50">
        <a class="navbar-brand js-scroll-trigger" href="/"></a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto my-2 my-lg-0">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/">Inicio</a>
              </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/about">CYTIES</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/servicios">Servicios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/centros">Centros y Laboratorios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/agend">Agenda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="/galeria">Galeria</a>
              </li>
          </ul>
        </div>
      </div>
    </nav>
      
    {% block content %}
    
    {% endblock %}

<!-- Footer -->
<footer class="page-footer font-small mdb-color lighten-3 pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
  
          <!-- Content -->
          <h5 class="font-weight-bold text-uppercase mb-4">CYTIES - Investigaci&oacute;n y Desarrollo</h5>
          <p>CYTIES Investigación y Desarrollo nace el 20 de octubre del año 2006, correspondiendo su
              nombre a la abreviatura de “Ciencia y Tecnología en Investigación Económica y Social”.</p>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-uppercase mb-4">Acerca de Nosotros</h5>
  
          <ul class="list-unstyled">
            <li>
              <p>
                <a href="#!">Inicio</a>
              </p>
            </li>
            <li>
              <p>
                <a href="/about">Acerca de Nosotros</a>
              </p>
            </li>
            <li>
              <p>
                <a href="/servicios">Servicios</a>
              </p>
            </li>
            <li>
              <p>
                <a href="/centros">Centros y Laboratorios</a>
              </p>
            </li>
            <li>
                <p>
                  <a href="/agend">Agenda</a>
                </p>
              </li>
              <li>
                  <p>
                    <a href="/galeria">Galeria</a>
                  </p>
                </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">
  
          <!-- Contact details -->
          <h5 class="font-weight-bold text-uppercase mb-4">Contacto</h5>
  
          <ul class="list-unstyled">
            <li>
              <p>
                <i class="fas fa-home mr-3"></i> Lima 360 Depto. 58 Edificio Los Sauces - Antofagasta, Chile</p>
            </li>
            <li>
              <p>
                <i class="fas fa-envelope mr-3"></i> contacto@cyties.cl - info@cyties.cl</p>
            </li>
            <li>
              <p>
                <i class="fas fa-phone mr-3"></i>56-55--2546874</p>
            </li>
            <li>
              <p>
                <i class="fas fa-print mr-3"></i>9 8504 8464</p>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
        <hr class="clearfix w-100 d-md-none">
  
        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 text-center mx-auto my-4">
  
          <!-- Social buttons -->
          <h5 class="font-weight-bold text-uppercase mb-4">S&iacute;guenos</h5>
          
          <ul class="list-unstyled">
              <li>
                  <a type="button" style="border-color:transparent" class="button" href="http://www.facebook.com/cytiesinvestigacionydesarrollo/">
                    <img class="rounded-circle" src="/media/static/facebook.png" height="50" >
                  </a>
              </li>
              <br>
              <br>
              <li>
                  <a type="button" class="btn-floating btn-tw" href="http://twitter.com/cyties">
                    <img src="/media/static/twitter.png" class="rounded-circle" height="50">
                  </a>
              </li>
              <br>
              <br>
              <li>
                  <a type="button" class="btn-floating btn-tw" href="#">
                    <img style="border-image: none" class="rounded-circle" src="/media/static/youtube.png" height="50"> 
              </li>
            </ul>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
    </div>
    <!-- Footer Links -->
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="/"> Seikotics - Asesor&iacute;as y Desarrollo </a>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->
</body> 
</html>

templates/galeria/galeria.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<br>

{% if imagen_list %}
<div class="container gallery-container">
  <h1 style="text-align:center;color: #1e4f99">Galeria Cyties - Investigaci&oacute;n y desarrollo</h1>
  <hr class="divider my-4">
  <br>
  <div class="tz-gallery">

      <div class="row">

          {% for imagen in imagen_list %}

          <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                  <a class="lightbox" href="{{imagen.imagen_archivo.url}}">
                      <img src="{{imagen.imagen_archivo.url}}" alt="{{imagen.nombre_imagen}}">
                  </a>
                  <div class="caption">
                      <h5>{{imagen.nombre_imagen}}</h5>
                      <p>{{imagen.descripcion_imagen}}</p>
                  </div>
              </div>
          </div>
          {% endfor %}

      </div>

  </div>

</div>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
{% else %}
<br>
<br>
<section>
    <div>
        <h1 style="text-align: center">No se encontraron imagenes </h1>
    </div>
    </section>
    {% endif %}  
{% endblock content %}

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{# CSS Bootstrap #}
{% bootstrap_css %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<section id="about">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2 style="text-align: center; color: #3081fa">CYTIES, Ciencia y Tecnología que crea el Desarrollo</h2>
              <hr class="divider my-4">
              <p class="lead" style="text-align: justify">Somos una empresa especializada en materia de investigación en Economía Aplicada al
                  Desarrollo, la Innovación y el Comercio Internacional que crea y gestiona conocimiento “Útil” para
                  la planificación, productividad y competitividad de nuestros clientes conforme ampliar el rango de
                  opciones de crecimiento económico y desarrollo sustentable.</p>
                  <p class="lead" style="text-align: justify">Desde el 2006 a la fecha, CYTIES ha realizado investigación aplicada en los más diversos ámbitos
                  de la economía y la sociedad, con el sello distintivo de la aplicación de sus servicios; esto con la
                  finalidad de “generar capacidades en las personas, las empresas, las instituciones, los sectores
                  económicos y los territorios que amplíen las oportunidades, la competitividad sistémica y el
                  desarrollo sustentable”.</p>
                  <br>
                  <img class="img-fluid rounded mx-auto d-block" alt="Responsive image" src="/static/img/imagen1.JPG"> 
                  <br>
            </div>
          </div>
        </div>
      </section>
      <section id="visionestrategica">
          <div class="container">
              <div class="row">
                <div class="col-lg-8 mx-auto">
                  <h2 style="text-align: center; color: #3081fa">Visi&oacute;n Estrategica</h2>
                  <hr class="divider my-4">
                  <p class="lead" style="text-align: justify">Nuestra empresa será reconocida como la principal fuente de información y gestión del conocimiento aplicado a la Innovación, el desarrollo de los Negocios y el Comercio Internacional 
                    del Norte de Chile y los Estados Subnacionales de los países miembros de la ZICOSUR.</p>
                <br>
                </div>
              </div>
            </div>
      </section>
    




{% endblock content %}

templates/pages/centros.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{# CSS Bootstrap #}
{% bootstrap_css %}
{% block content %}
<br>
<br>
<br>
<br>
<section id="centros">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto">
              <h2 style="text-align: center; color: #3081fa" >Centros y Laboratorios</h2>
              <hr class="divider my-4">
              <p class="lead" style="text-align: justify">Como corolario de la gestión internacional, CYTIES dispone del Centro de Inteligencia de Negocios 
                Internacionales ZICOSUR – Asia Pacífico el que además cuenta con el NODO Exportador para las
                 PYMES y el Laboratorio Interactivo de Innovación & Ciencias Empresariales.</p>
                 <br>
                 <img src="/media/static/zicosur.png" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
                <br>
                 <p class="lead" style="text-align: justify">Esto constituye a CYTIES en una empresa de base tecnológica, configurando una
                    ventaja competitiva sostenible en la agregación de valor a los procesos de investigación, 
                    oportunidades de negocios, comercio exterior, modelamiento de negocios internacionales
                     y la gestión integral de proyectos a partir del análisis estadístico de Metadatas de 
                     las economías de 23 países a las que aplicando la metodología de Bussiness Intelligence,
                      permite la elaboración de Macro Proyectos de Inversión, Atracción de Inversiones, 
                      Joint Venture, Franquicias, Licenciamientos y desarrollo de Patentes mediante procesos 
                      de Innovación Secuencial, Disruptiva e Inversa.</p>
                <p class="lead" style="text-align: justify">Lo anterior, ha conllevado dos importantes hitos en la gestión empresarial el año 2017.
                 La firma del Convenio Marco de Cooperación Internacional con la Asociación Comercial e Industrial
                  de Campo Grande MS Brasil, ACICG y, el Premio “Mejor PYME: Mejores Negocios”, entregado por la 
                  Corporación de Fomento de la Producción, CORFO. Ambos hitos, proveen las bases de la gestión a 
                  desarrollar en el periodo 2018 – 2022, estructurando el conjunto de servicios que le invitamos 
                  a conocer en este Book corporativo.</p>
                  <br>
                 <img src="/media/static/LOGO-CYTIES-RETOQUES-MAYO PNG.png" class="img-fluid rounded mx-auto d-block" alt="Responsive image">
                <br>
                <br>
            </div>
          </div>
        </div>
      </section>     
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{# CSS Bootstrap #}
{% bootstrap_css %}
{% block content %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/static/img/imagen1.JPG" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/img/infografia.jpg" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/static/img/infografia.jpg" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <div class="carousel-caption d-none d-md-block">
      <h1>“CYTIES, Ciencia y Tecnología que crea el desarrollo…”</h1>
    <p>Somos una empresa especializada en materia de investigación en Economía Aplicada al
      Desarrollo, la Innovación y el Comercio Internacional que crea y gestiona conocimiento “Útil” para
      la planificación, productividad y competitividad de nuestros clientes conforme ampliar el rango de
      opciones de crecimiento económico y desarrollo sustentable.</p>
    <a class="btn btn-primary" role="button" href="/about">Seguir Leyendo</a>
    </div>
  </div>


{% endblock content %}

templates/pages/servicios.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<br>
<br>
<br>
<br>
<!-- Services Section -->
<section class="page-section" id="services">
    <div class="row">
        <div class="col-lg-8 mx-auto">
          <h2 style="text-align: center; color: #3081fa">Servicios</h2>
          <p class="lead" style="text-align: justify"> Los servicios comprenden el diseño y la realizaci&oacute;n completa de estudios, asesor&iacute;as, 
              consultor&iacute;as y procesos de formaci&oacute;n, capacitaci&oacute;n y perfeccionamiento, adem&aacute;s de una alta 
              capacidad en la formulaci&oacute;n, implementaci&oacute;n y gesti&oacute;n integral de proyectos y en la gesti&oacute;n 
              de negocios internacionales en los m&aacute;s diversos &aacute;mbitos y &aacute;reas del conocimiento</p>
        </div>
      </div>
      <hr class="divider my-4">
      <div class="container">
          <h2 class="text-center mt-0" style="color: #3081fa">Servicios destacados</h2>
          <hr class="divider my-4">
          <div class="row">
            <div class="col-lg-4 col-md-9 text-center">
              <div class="mt-5">
                  <img src="/media/static/IMAGEN SERVICIO DE INVESTIGACION APLICADA AZUL.png" class="img-fluid" alt="Responsive image">
                <h3 class="h4 mb-2">Investigaci&oacute;n Aplicada Multim&eacute;todo</h3>
                <p class="text-muted mb-0">Ofrecemos un servicio de gesti&oacute;n del conocimiento para la creaci&oacute;n y sistematizaci&oacute;n de 
                  datos que generen informaci&oacute;n para la toma de decisiones del sector empresarial y del sector p&uacute;blico. Actualmente 
                  contamos con bases de datos del comercio exterior de 23 pa&iacute;ses, lo que nos permite disponer una Miner&iacute;a de Datos 
                  (Data Warehouse y Big Data) procesados mediante una Estrategia de Business Intelligence.</p>
              </div>
            </div>
            <div class="col-lg-4 col-md-9 text-center">
              <div class="mt-5">
                  <img src="/media/static/internacional.png" class="img-fluid" alt="Responsive image">
                <h3 class="h4 mb-2" >Gesti&oacute;n de Negocios Internacionales</h3>
                <p class="text-muted mb-0">Desde la prospecci&oacute;n de los mercados a la determinaci&oacute;n de productos y/o servicios, 
                  incluyendo la mercadotecnia y la log&iacute;stica asociada y, la internacionalizaci&oacute;n de las empresas (PYMES) y su 
                  participaci&oacute;n en las amplias opciones de los negocios internacionales según su potencial y capacidad.</p>
              </div>
            </div>
            <div class="col-lg-4 col-md-9 text-center">
              <div class="mt-5">
                  <img src="/media/static/IMAGEN SERVICIO DE GESTION INTEGRAL.png" class="img-fluid" alt="Responsive image">
                <h3 class="h4 mb-2">Gestión Integral de Proyectos.</h3>
                <p class="text-muted mb-0" >Individuales y/o asociativos de tipo productivo, comercial, de infraestructura,
                   tecnología e innovación mediante la metodología Project Management.</p>
              </div>
            </div>
            <div class="col-lg-4 col-md-9 text-center">
              <div class="mt-5">
                  <img src="/media/static/IMAGEN SERVICIO DE ASISTENCIA TECNICA.png" class="img-fluid" alt="Responsive image">
                <h3 class="h4 mb-2">Asistencia Técnica.</h3>
                <p class="text-muted mb-0">En materias especializadas a la planificación, la internacionalización empresarial, el diseño de 
                  la oferta exportable, la conformación de consorcios exportadores, misiones comerciales, ruedas de negocios,
                   sistemas de seguimiento y evaluación. Es decir, abordar todo lo relativo a la cadena de valor productivo de las 
                   empresas y al diseño de instrumentos de planificación desde el sector público.</p>
              </div>
            </div>
            <div class="col-lg-4 col-md-9 text-center">
                <div class="mt-5">
                    <img src="/media/static/IMAGEN SERVICIO DE CAPACITACION AZUL.png" class="img-fluid" alt="Responsive image">
                  <h3 class="h4 mb-2">Formación, Capacitación y Perfeccionamiento</h3>
                  <p class="text-muted mb-0">Focalizada en el capital humano gerencial de las empresas y de los ejecutivos
                     de negocios. Para ello disponemos del Laboratorio Interactivo de Innovación y Ciencias Empresariales 
                     que cuenta con equipos tecnológicos y softwares de última generación para dar respuestas a las más 
                     altas exigencias de los estándares internacionales de la industria.</p>
                </div>
              </div>
          </div>
        </div>
      </section>

{% endblock content %}